Bump dune language to 3.16 and necessary dune lang changes
1. Remove unused ppxlib dependency in dune files. Else, we see,

```
12 |   (pps lwt_ppx ppx_let ppx_deriving.std ppx_deriving_yojson ppxlib ppx_expect
                                                                 ^^^^^^
Error: Ppx dependency on a non-ppx library "ppxlib". If "ppxlib" is in fact a
ppx rewriter library, it should have (kind ppx_rewriter) in its dune file.
```

2. Remove now obsolete `(allow_approximate_merlin)`