Bump ocaml compiler version and necessary deps
Vendor cmdliner because we need ~stop_on_pos
Update esy-solve-cudf submodule
Vendor logs, fmt too

IMPORTANT: pin lwt because 5.6.1 doesn't spawn processes on Windows properly

Ex:

```
      Error: Command failed: D:\a\1\s\_build\install\default\bin\esy.exe install
      info install 0.6.14 (using package.json)
      info resolving esy packages: done
      error: Error occured during ChildProcess.executeCmd: Invalid argument CreateProcess
```

or `Fatal error: Not_found`

wip

run fmt